version: '3'
services:
  # 
  asn:
    # 
    build: cse-asn
    # restart the container if a crash occurs but stop when stopped by user
    restart: unless-stopped
    # set the time zone
    environment:
      - TZ=Europe/Vienna
    #
    ports:
      - "8080:8080"
    volumes:
      - ./cse-asn/acme.ini:/ACME-oneM2M-CSE/ACME-oneM2M-CSE-master/acme.ini
      - ./cse-asn/mio_flex.fcp:/ACME-oneM2M-CSE/ACME-oneM2M-CSE-master/init/mio_flex.fcp
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
  ae:
    build: AE
    # restart the container if a crash occurs but stop when stopped by user
    restart: unless-stopped
    # set the time zone
    environment:
      - TZ=Europe/Vienna
    depends_on:
      - asn
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/mem:/dev/mem
    cap_add:
      - SYS_RAWIO
    volumes:
      - ./AE/AE_Application.py:/AE_Application.py
      - ./AE/ae.ini:/ae.ini
      - ./AE/CreateStructure.py:/CreateStructure.py
      - ./AE/LedPwm.py:/LedPwm.py
      - ./AE/NotificationServerSmall.py:/NotificationServerSmall.py
      - ./AE/Scale.py:/Scale.py
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
