version: '3'
services:
  # 
  asn:
    # 
    build: cse-in
    # restart the container if a crash occurs but stop when stopped by user
    restart: unless-stopped
    # set the time zone
    environment:
      - TZ=Europe/Vienna
    #
    ports:
      - "8080:8080"
    volumes:
      - ./cse-in/acme.ini:/ACME-oneM2M-CSE/ACME-oneM2M-CSE-0.12.0/acme.ini
      - ./cse-in/mio_flex.fcp:/ACME-oneM2M-CSE/ACME-oneM2M-CSE-0.12.0/init/mio_flex.fcp
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket