version: '3'
services:
  # 
  in:
    # 
    build: cse-in
    # restart the container if a crash occurs but stop when stopped by user
    depends_on:
      - nodered
    restart: unless-stopped
    # set the time zone
    environment:
      - TZ=Europe/Vienna
    #
    ports:
      - "8080:8080"
    volumes:
      - ./cse-in/acme.ini:/ACME-oneM2M-CSE/ACME-oneM2M-CSE-0.12.0/acme.ini
      - ./cse-in/mio_flex.fcp:/ACME-oneM2M-CSE/ACME-oneM2M-CSE-0.12.0/init/mio_flex.fcp
      - ./certs-keys/server.crt:/ACME-oneM2M-CSE/ACME-oneM2M-CSE-0.12.0/server.crt
      - ./certs-keys/server.key:/ACME-oneM2M-CSE/ACME-oneM2M-CSE-0.12.0/server.key
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

  nodered:
    #
    build: nodered
    # restart the container if a crash occurs but stop when stopped by user
    restart: unless-stopped
    # set the time zone
    environment:
      - TZ=Europe/Vienna
    #
    ports:
      - "1880:1880"
    volumes:
      - ./certs-keys/server.crt:/data/server.crt
      - ./certs-keys/server.key:/data/server.key
      - ./certs-keys/demoCA/cacert.pem:/data/ca.crt
      - ./nodered/data:/data
#      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket

