FROM nodered/node-red:latest
#COPY package.json .
#RUN npm install --unsafe-perm --no-update-notifier --no-fund --only=production

#RUN cd /usr/scr/node-red && npm install -g npm@10.2.2

#RUN cd /usr/scr/node-red && npm install --save node-red-node-smooth

#RUN npm install node-red-node-smooth


RUN npm install node-red-dashboard

#RUN cd /usr/src/node-red && npm install --save node-red-contrib-influxdb

#WORKDIR /usr/scr/node-red

